name: Check, Build and Publish Package

on: push

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: "latest"
      
      - name: Setup a local virtual environment
        run: |
          export PATH="~/.local/bin:$PATH"
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local

      - uses: actions/cache@v3
        name: Define a cache for poetry
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}

      - name: Install the project dependencies
        run: |
          export PATH="~/.local/bin:$PATH"
          poetry install

      - name: Activate Virtual Env
        run: |
          export PATH="~/.local/bin:$PATH"
          poetry env activate

      - name: Run MyPy
        run: |
          export PATH="~/.local/bin:$PATH"
          poetry run mypy .

      - name: Run the Formatter checks
        run: |
          export PATH="~/.local/bin:$PATH"
          poetry run black . --check

      - name: Run the Tests
        run: |
          export PATH="~/.local/bin:$PATH"
          poetry run pytest . -v

      - name: Check Package
        run: |
          export PATH="~/.local/bin:$PATH"
          poetry check

      - name: Build Package
        run: |
          export PATH="~/.local/bin:$PATH"
          poetry build

      - name: Upload the Package Build as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FFLib
          path: ./dist

  publish:
    needs: check-and-build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')  # Ensure it only runs on version tags
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Twine
        run: python -m pip install --upgrade twine

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: FFLib
          path: ./dist

      - name: Publish package to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: "New release of the FFLib! 📦🚀"
          draft: false
          prerelease: false
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}